### ISSUE TITLE
RGB color mode is equal to BW for some scanner

### ISSUE THREAD

**Issue by qwqVictor** [nagimov/wia-cmd-scanner#2]
My printer and scanner model is Canon MF3200 Series.

The color mode RGB is equal to BW mode for my Canon MF3200 Series.

Maybe the color code 1 for RGB is not proper for all scanners.

I suggest that to allow user to specify the color code instead of converting the string to the color code inside could be much better.

And I'm always glad to help.

(I'd like to modify it by myself, but I'm a macOS user that has no Visual Studio Express, I use it just for a project for myself to use the device which is not supported by macOS, and the project is also GPL-3.0 too.)

**Comment by qwqVictor** [comment]
I know what just happened, you forgot to set the property of id 4104, which decides the color depth of scanning. 

I have fixed it. Please see [#3](https://github.com/nagimov/wia-cmd-scanner/pull/3).

**Comment by nagimov** [comment]
Specifying color depth is redundant if RGB/GRAY/BW is already specified. I kept `/color` flag and matched WIA property accordingly.
Please let me know if the latest binary fixes it for you: https://github.com/nagimov/wia-cmd-scanner/releases/download/0.2.1/wia-cmd-scanner-0.2.1.zip
Thanks!

**Comment by qwqVictor** [comment]
Great job! Your project helped me lot, without this I can't implement the scanning port of [PDFPrinter-WinPHP](https://github.com/qwqVictor/PDFPrinter-WinPHP).
Now it's got the ending. let's close this issue and go on!
